FROM microsoft/dotnet:sdk AS build-env
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore

# Copy everything else and build
COPY . ./
RUN dotnet publish -c Release -o out

# Build runtime image
FROM microsoft/dotnet:sdk
WORKDIR /app
COPY --from=build-env /app/out .
RUN echo "{ \"ConnectionStrings\": { \"BaseProject\": \"Server=lesson08.database.windows.net;Database=BaseProject_Dan_Docker;User Id=aca;Password=singer#1;MultipleActiveResultSets=true\" } }" > appsettings.Production.json

ARG Microsoft__Key
ARG Microsoft__Secret
ENV ASPNETCORE_URLS http://0.0.0.0:80;https://0.0.0.0:443 

CMD ["dotnet", "BaseProject.dll"]